In [22]:
import numpy as np
# np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [23]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [24]:
print("x3: ", x3)

x3:  [[[3 9 7 6 6]
  [2 3 6 0 8]
  [0 7 6 5 9]
  [6 5 2 7 1]]

 [[9 2 2 5 6]
  [4 2 2 1 0]
  [9 0 2 8 3]
  [0 8 8 1 0]]

 [[5 8 2 3 5]
  [3 8 6 4 6]
  [3 6 2 6 5]
  [5 9 4 6 5]]]
